# Generated by Django 3.2.6 on 2021-08-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrder',
            fields=[
                ('id_estado_order', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio_producto', models.IntegerField()),
                ('descripcion_producto', models.CharField(max_length=150)),
                ('cantidad_inventario', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('super_user', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_total', models.IntegerField()),
                ('address_order', models.CharField(max_length=150)),
                ('estado_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.estadoorder')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesOrder',
            fields=[
                ('id_detalles_order', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor_total', models.IntegerField()),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.inventario')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.order')),
            ],
        ),
    ]
