# Generated by Django 3.2.6 on 2021-08-25 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrder',
            fields=[
                ('id_estado_order', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_person', models.BigIntegerField()),
                ('precio_total', models.IntegerField()),
                ('address_order', models.CharField(max_length=150)),
                ('estado_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.estadoorder')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesOrder',
            fields=[
                ('id_detalles_order', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_producto', models.BigIntegerField()),
                ('cantidad', models.IntegerField()),
                ('valor_total', models.IntegerField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidosApp.order')),
            ],
        ),
    ]
